### ISSUE TITLE
Cannot initialize plugins

### ISSUE THREAD

**Issue by stephanmg** [VRL-Studio/VRL-UG#1]
Hi,

I installed VRL-UG according to the instructions in the README. I built ug4 with `-DTARGET=VRL` and `-DEMBEDDED_PLUGINS=ON` from the current HEAD revision of the ugcore repository.

`cmake ..` from my build folder:
```
-- 
-- Info: Current options:
-- Info: TARGET:            vrl (options are: ugshell, libug4, vrl, vrlgrid, libgrid, gridshell, ugplugin, amg, luashell)
-- Info: DIM:               ALL (options are: 1, 2, 3, ALL, "1;2", "1;3", "2;3")
-- Info: CPU:               ALL (options are: 1, 2, 3, 4, 5, VAR, ALL, "2;4", "1;3;4" , ...)
-- Info: PRECISION:         double (options are: single, double)
-- Info: STATIC_BUILD:      OFF (options are: ON, OFF)
-- Info: DEBUG:             OFF (options are: ON, OFF)
-- Info: DEBUG_LOGS:        OFF (options are: ON, OFF)
-- Info: PARALLEL:          OFF (options are: ON, OFF)
-- Info: PCL_DEBUG_BARRIER: OFF (options are: ON, OFF)
-- Info: PROFILER:          None (options are: None, Shiny, Scalasca, Vampir, ScoreP)
-- Info: PROFILE_PCL:       OFF (options are: ON, OFF)
-- Info: CPU_FREQ:          OFF (options are: ON, OFF)
-- Info: PROFILE_BRIDGE:    OFF (options are: ON, OFF)
-- Info: LAPACK:            OFF (options are: ON, OFF)
-- Info: BLAS:              OFF (options are: ON, OFF)
-- Info: INTERNAL_BOOST:    ON (options are: ON, OFF)
-- Info: EMBEDDED_PLUGINS   ON (options are: ON, OFF)
-- Info: COMPILE_INFO       ON (options are: ON, OFF)
-- Info: USE_LUA2C          OFF (options are: ON, OFF)
-- Info: USE_LUAJIT         OFF (options are: ON, OFF)
-- 
-- Info: External libraries (path which contains the library or ON if you used uginstall):
-- Info: TETGEN:   
-- Info: HLIBPRO:  
-- 
-- Info: C   Compiler: /usr/lib/ccache/cc (ID: GNU)
-- Info: C++ Compiler: /usr/lib/ccache/c++ (ID: GNU)
-- 
-- Info: Using CPU Algebra.
-- Info: compiling with cxx flags:  -Wall -Wno-multichar -Wno-unused-local-typedefs -Wno-maybe-uninitialized -O3 -DNDEBUG -funroll-loops -ftree-vectorize
-- Info: compiling with c flags:  -Wall -Wno-multichar -Wno-unused-local-typedefs -Wno-maybe-uninitialized -O3 -DNDEBUG -funroll-loops -ftree-vectorize
-- Info: Not using LAPACK, use -DLAPACK=ON to enable.
-- Info: Not using BLAS, use -DBLAS=ON to enable.
-- Info: Internal Boost 
-- Info: Including Boost from /home/stephan/Code/git/ug4/ugcore/cmake/../../externals/BoostForUG4/
-- Info: COMPILE_INFO enabled. Causes relinking on each run of make.
-- 
-- Info: Enabled plugins:
--       neuro_collection, 
-- Info: Disabled plugins:
--       LuaShell, ProMesh, 
-- 
-- Hint: To enable/disable a plugin 'PLUGIN_NAME' use the cmake option: -DPLUGIN_NAME=ON/OFF
-- 
-- Additional options for the neuro_collection plugin (-DNC for setting options):
--       Testsuite:   OFF (options are: ON, OFF)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stephan/Code/git/ug4/build_vrl
```

After building VRL-UG and installing it in VRL-Studio I am given the following error messages:

![2020-08-24-140424_1920x1080_scrot](https://user-images.githubusercontent.com/1750463/91042897-d5dc3600-e612-11ea-8f0c-51cef26786f0.png)

```
 -- UG(NONE) -- 
java.lang.ClassNotFoundException: edu.gcsc.vrl.ug.api.UGAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at edu.gcsc.vrl.ug.UG.findCompatibleAPI(UG.java:766)
        at edu.gcsc.vrl.ug.UG.<init>(UG.java:644)
        at edu.gcsc.vrl.ug.UG.getInstance(UG.java:872)
        at edu.gcsc.vrl.ug.UG.getInstance(UG.java:910)
        at edu.gcsc.vrl.ug.Configurator.init(Configurator.java:455)
        at eu.mihosoft.vrl.system.VRL.initPlugins(VRL.java:605)
        at eu.mihosoft.vrl.system.VRL.initAll(VRL.java:334)
        at eu.mihosoft.vrlstudio.main.Studio.main(Studio.java:2537)
>> loading native libraries:
 --> done.
Aug 24, 2020 2:01:35 PM eu.mihosoft.vrl.system.VRL initPlugins
SEVERE: null
java.lang.UnsatisfiedLinkError: edu.gcsc.vrl.ug.UG._ugInit([Ljava/lang/String;)I
        at edu.gcsc.vrl.ug.UG._ugInit(Native Method)
        at edu.gcsc.vrl.ug.UG.ugInit(UG.java:1898)
        at edu.gcsc.vrl.ug.UG.connectToNativeUG(UG.java:465)
        at edu.gcsc.vrl.ug.UG.<init>(UG.java:652)
        at edu.gcsc.vrl.ug.UG.getInstance(UG.java:872)
        at edu.gcsc.vrl.ug.UG.getInstance(UG.java:910)
        at edu.gcsc.vrl.ug.Configurator.init(Configurator.java:455)
        at eu.mihosoft.vrl.system.VRL.initPlugins(VRL.java:605)
        at eu.mihosoft.vrl.system.VRL.initAll(VRL.java:334)
        at eu.mihosoft.vrlstudio.main.Studio.main(Studio.java:2537)

```

Could anybody, possibly, @miho or @bsumirak assist in this problem?

Best wishes,
Stephan

P.S.: The full log from console:
```
>> starting with no param
>> detected x86 (64 bit) os
>> using java executable from: jre/x64/bin/java
Picked up JAVA_TOOL_OPTIONS: 
>> init Studio.class logger
Aug 24, 2020 2:01:33 PM eu.mihosoft.vrlstudio.main.Studio main
INFO: AppFolder: /home/stephan/Downloads/VRL-Studio
>> VRL Version: 0.4.4.0.3, build: 2018/10/31 13:49:41
 --> running on Java Version: 1.8.0_152 (Oracle Corporation)
 --> OS: Linux (x64)
 --> pid: 7625
>> Property Folder Options:
 --> using property folder template, path: resources/studio-resources//property-folder-template
 --> using custom property folder suffix, suffix: default
 --> initializing property folder: /home/stephan/.vrl/0.4.4/default
>> installing payload plugins: [failed]
 --> project main class not found (assuming there is no project)
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/gluegen-rt-natives-linux-amd64.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/gluegen-rt-natives-windows-amd64.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/args4j-2.0.21.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/gluegen-rt-natives-windows-i586.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/VRL.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/jpedal_lgpl.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/gluegen-rt.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/jogl-all-natives-windows-amd64.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/gluegen.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/jogl-all.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/gluegen-rt-natives-macosx-universal.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/jogl-all-natives-macosx-universal.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/jogl-all-natives-linux-i586.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/gluegen-rt-natives-linux-i586.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/bcpg-jdk15on-147.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/jogl-all-natives-windows-i586.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/glg2d-0.5-SNAPSHOT.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/bcprov-jdk15on-147.jar" to system classpath
>> adding "file:/home/stephan/Downloads/VRL-Studio/.application/lib/jogl-all-natives-linux-amd64.jar" to system classpath
>> ClassPathUpdater.addAllJarsInDir("custom-lib"): directory does not exist!
>> Plugin Options:
 --> disabling checksum test
 --> no plugin path specified, using default.
>> loading plugin from cache
 --> plugin "VRL-UG" found
--> plugin = "VRL-UG-0.2.2" already installed. Skipping installation.
>> loading plugin from cache
 --> plugin "VRL-VRN-Generator" found
--> plugin = "VRL-VRN-Generator-0.0.1" already installed. Skipping installation.
>> loading plugin from cache
 --> plugin "Groovy-Support" found
>> loading plugin from cache
 --> plugin "VRL-JFreeChart" found
>> Init Plugins ( #5 )
>> Plugin (1): VRL-0.4.4.0.3
>> Plugin (2): VRL-JFreeChart-0.2.5.1
>> Plugin (3): Groovy-Support-0.1
>> Plugin (4): VRL-UG-0.2.2
 -- UG(NONE) -- 
java.lang.ClassNotFoundException: edu.gcsc.vrl.ug.api.UGAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at edu.gcsc.vrl.ug.UG.findCompatibleAPI(UG.java:766)
        at edu.gcsc.vrl.ug.UG.<init>(UG.java:644)
        at edu.gcsc.vrl.ug.UG.getInstance(UG.java:872)
        at edu.gcsc.vrl.ug.UG.getInstance(UG.java:910)
        at edu.gcsc.vrl.ug.Configurator.init(Configurator.java:455)
        at eu.mihosoft.vrl.system.VRL.initPlugins(VRL.java:605)
        at eu.mihosoft.vrl.system.VRL.initAll(VRL.java:334)
        at eu.mihosoft.vrlstudio.main.Studio.main(Studio.java:2537)
>> loading native libraries:
 --> done.
Aug 24, 2020 2:01:35 PM eu.mihosoft.vrl.system.VRL initPlugins
SEVERE: null
java.lang.UnsatisfiedLinkError: edu.gcsc.vrl.ug.UG._ugInit([Ljava/lang/String;)I
        at edu.gcsc.vrl.ug.UG._ugInit(Native Method)
        at edu.gcsc.vrl.ug.UG.ugInit(UG.java:1898)
        at edu.gcsc.vrl.ug.UG.connectToNativeUG(UG.java:465)
        at edu.gcsc.vrl.ug.UG.<init>(UG.java:652)
        at edu.gcsc.vrl.ug.UG.getInstance(UG.java:872)
        at edu.gcsc.vrl.ug.UG.getInstance(UG.java:910)
        at edu.gcsc.vrl.ug.Configurator.init(Configurator.java:455)
        at eu.mihosoft.vrl.system.VRL.initPlugins(VRL.java:605)
        at eu.mihosoft.vrl.system.VRL.initAll(VRL.java:334)
        at eu.mihosoft.vrlstudio.main.Studio.main(Studio.java:2537)

>> Plugin (5): VRL-VRN-Generator-0.0.1
>> 3D Options:
 --> enabling 3D rendering
>> Graphics2D config:
 --> type not specified, using system default
>> Debugging Options:
 --> Warning: no debugging option specified! Default: no
>> register plugins with canvas: 
 --> VRL-0.4.4.0.3 (ok)
 --> Groovy-Support-0.1 (ok)
>> Default Project Options:
 --> using specified default project file: default.vrlp
>> VRLUpdater: checking for updates: http://vrl-studio.mihosoft.eu/updates/linux/repository.xml
>> VRLUpdater: downloading repository signature 0.0%
>> VRLUpdater: downloading repository signature100.0%
 --> repository signature download finished. /home/stephan/.vrl/0.4.4/default/tmp/0/bf7aaf0f-792b-4d21-be59-a9f0907d395b/repository.xml.asc, size: 0.2939453125 KB
>> VRLUpdater: downloading repository 0.0%
>> VRLUpdater: downloading repository 100.0%
 --> repository download finished. /home/stephan/.vrl/0.4.4/default/tmp/0/bf7aaf0f-792b-4d21-be59-a9f0907d395b/repository.xml, size: 6.1171875 KB
>> VRLUpdater: repository successfully verified.
>> VRLUpdater: searching repository.xml for updates:
```

**Comment by stephanmg** [comment]
Non-issue. The natives.zip must contain the binaries directly (And not within any subfolder).
